POST http://localhost:3000/question
Content-Type: application/json

{
  "title": "a title",
  "content": "Some content",
  "tags": ["tag1", "tag2"]
}

###
GET http://localhost:3000/questions
Accept: application/json

###
GET http://localhost:3000/questions/1
Accept: application/json

###
GET http://localhost:3000/blargh
Accept: application/json
